### ISSUE TITLE
Base project setup

### ISSUE THREAD

**Issue by dmytroleonov** [Dmytro-Leonov/TestsWebsite#1]
# TODO
- [x] Create list of project features
- [x] Create ER diagram
- [x] Set up a database
- [x] Start project
